spring:
  profiles:
    active: dev

---

spring:
  profiles: dev

message.response:   Hello from DEV spring boot properties

kafka.broker: localhost:9092,localhost:9093,localhost:9094
enable.auto.commit: true
auto.commit.interval.ms:  100
group.id: group1
kafka.auto.offset.reset: earliest
kafka.topic: my-topic


---

spring:
  profiles: stage

message.response:   Hello from STAGE spring boot properties

---

spring:
  profiles: prod

message.response:   Hello from PROD spring boot properties


---